apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  # - path: cert-manager-patch.yaml
  #   target:
  #     kind: OCIRepository
  #     name: cert-manager
  #     namespace: flux-system
  # - path: external-dns-patch.yaml
  #   target:
  #     kind: OCIRepository
  #     name: external-dns
  #     namespace: flux-system
  - path: kgateway-crds-patch.yaml
    target:
      kind: OCIRepository
      name: kgateway-crds
      namespace: flux-system
  - path: kgateway-patch.yaml
    target:
      kind: OCIRepository
      name: kgateway
      namespace: flux-system

