apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway
  namespace: flux-system
spec:
    values:
      controller:
        image:
          registry: "cr.kgateway.dev/kgateway-dev"
          repository: kgateway
          tag: "v2.1.2"
      image:
        registry: cr.kgateway.dev/kgateway-dev
        tag: "v2.1.2"
      inferenceExtension:
        enabled: true