---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-inference-extension-crds
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  wait: false
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: gateway-api-inference-extension-crds
  path: ./config/crd/bases