---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3-8b-disagg-epp
  labels:
    app: qwen3-8b-disagg-epp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen3-8b-disagg-epp
  template:
    metadata:
      labels:
        app: qwen3-8b-disagg-epp
    spec:
      serviceAccountName: epp-sa
      terminationGracePeriodSeconds: 130

      imagePullSecrets:
        - name: docker-imagepullsecret

      containers:
        - name: epp
          image: nvcr.io/nvstaging/ai-dynamo/gaie-epp-dynamo:v0.6.0-1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"
          command: ["/bin/sh", "-c"]
          args:
            - >
              exec /epp
              -poolName "llama3-70b-agg-pool"
              -poolNamespace "$POD_NAMESPACE"
              -v 4 --zap-encoder json
              -grpcPort 9002 -grpcHealthPort 9003
              -configFile /etc/epp/epp-config-dynamo.yaml
          volumeMounts:
            - name: epp-config
              mountPath: /etc/epp
              readOnly: true

          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PLATFORM_NAMESPACE
              value: "$(POD_NAMESPACE)" # set to your dynamo platform namespace if different
            - name: ETCD_ENDPOINTS
              value: "dynamo-platform-etcd.$(PLATFORM_NAMESPACE):2379" #  update dynamo-platform to appropriate namespace
            - name: NATS_SERVER
              value: "nats://dynamo-platform-nats.$(PLATFORM_NAMESPACE):4222" #  update dynamo-platform to appropriate namespace
            - name: DYNAMO_NAMESPACE
              value: "$(POD_NAMESPACE)-llama3-70b-agg"
            - name: DYNAMO_MODEL
              value: "RedHatAI/Llama-3.3-70B-Instruct-FP8-dynamic"
            - name: DYNAMO_KV_BLOCK_SIZE
              value: "128" # UPDATE to match the --block-size in your deploy.yaml engine command
            - name: USE_STREAMING
              value: "true"

          ports:
            - containerPort: 9002
            - containerPort: 9003
            - name: metrics
              containerPort: 9090
          livenessProbe:
            grpc:
              port: 9003
              service: inference-extension
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            grpc:
              port: 9003
              service: inference-extension
            initialDelaySeconds: 5
            periodSeconds: 10

      volumes:
        - name: epp-config
          configMap:
            name: epp-config
            items:
              - key: epp-config-dynamo.yaml
                path: epp-config-dynamo.yaml